# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: AirflowTask

  steps:
  - script: echo Airflow Task is succesfull
  #- script: exit 1

  - task: Bash@3
    inputs:
      targetType: inline
      script: echo task 1 bash

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: azure-script-test.py