# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: AirflowTask

  steps:
  - script: echo Hello!

- job: TestScript
  dependsOn: AirflowTask
  condition: succeeded() # this job will only run if AirflowTask is Succesfull

